### ISSUE TITLE
Critical bug: picture removed nodes

### ISSUE THREAD

**Issue by ssdaniel24** [sfence/painting#5]
Placing picture at occupied pos is possible:
![2024-06-10_20-47-20](https://github.com/sfence/painting/assets/107036969/1d28c06c-915b-4539-b0bd-f33972dfb492)
![2024-06-10_20-47-23](https://github.com/sfence/painting/assets/107036969/23d76231-fdb4-4cd9-a23a-f216cae2877d)

Note: **Removing protected nodes is also possible**.

**Comment by sfence** [comment]
Fixed by 17edd64
