### ISSUE TITLE
Crash when placing legacy paintings

### ISSUE THREAD

**Issue by ssdaniel24** [sfence/painting#7]
Game crashes when player tries to place old painting with legacy picture format (55a809a) from his inventory.

Mod tries to decode base64 that does not exist in legacy picture meta data.

**Comment by sfence** [comment]
So, if I understand well, this happens when updating from the Painting mod older than the last 0.9 version from the original author (https://forum.minetest.net/viewtopic.php?t=2588)?

**Comment by sfence** [comment]
Fixed by 3779a08.

**Comment by sfence** [comment]
Work with inventory pictures from 0.9.0 version but crashes with inventory pictures from 55a809a.

**Comment by sfence** [comment]
Bad version usage on reporter side,works. Closed.
